x = int(input("Podaj liczbę 1: "))
y = int(input("Podaj liczbę 2: "))
suma = str(x + y)
roznica = str(x - y)
iloczyn = str(x * y)
iloraz = str(x / y)
print("Suma"+ " " + suma)
print("Róznica"+ " " + roznica)
print("Iloczyn"+ " " + iloczyn)
print("Iloraz"+ " " + iloraz)
