tup1 = (1, 'dwa', 3, 'cztery', 5, 'sześć')
print(tup1)
print("Długość:", len(tup1))
print("Miejsce w pamięci:",id(tup1))
tup1 = tup1 + (7, 'osiem')
print("Dodanie dwóch el.:",tup1)
print("Miejsce w pamięci:",id(tup1))
print("Krotka:",tup1)
tup_1 = list(tup1)
print("Lista:",tup_1)